"""
extract_na_ids.py
Generates a LAMMPS include file that defines the group 'former_Na':
the K atoms in IOX2 that originally were Na in the AM_x{parent} glass.

Since STAGE4 uses  set type 4 type 5  (ALL Na→K, IDs preserved),
the K atoms that came from Na are exactly those whose atom ID was
type 4 (Na) in the parent as-melted file.

Usage:
    python3 extract_na_ids.py <x_parent> <r>

Outputs:
    id_files/na_ids_xp{x_parent}_r{r}.lmp
    — contains a sequence of  group former_Na id ...  lines
      (50 IDs per line, using & continuation) that LAMMPS can include.

Atom types: Si=1, O=2, Ca=3, Na=4, K=5
"""

import sys
from pathlib import Path

IDS_PER_LINE = 50   # LAMMPS line-length safety margin

AM_DATA = (Path(__file__).parent.parent
           / "STAGE1_MELTQUENCH" / "data" / "asmelted_723K"
           / "AsMelted_723K_x{xp}_r{r}_PMMCS_rc8p0.data")

OUT_DIR = Path(__file__).parent / "id_files"


def read_na_ids(path):
    """Return sorted list of atom IDs that have type 4 (Na)."""
    na_ids = []
    in_atoms = False
    with open(path, encoding='utf-8', errors='replace') as f:
        for line in f:
            s = line.strip()
            if not s:
                continue
            if s.startswith('Atoms'):
                in_atoms = True
                continue
            if in_atoms:
                parts = s.split()
                if len(parts) < 2:
                    continue
                try:
                    atom_id  = int(parts[0])
                    atom_typ = int(parts[1])
                except ValueError:
                    continue
                if atom_typ == 4:
                    na_ids.append(atom_id)
    return sorted(na_ids)


def write_lammps_group(na_ids, out_path):
    """Write a LAMMPS include file defining group 'former_Na'."""
    if not na_ids:
        raise ValueError("No Na atoms found — check data file and atom types.")

    lines = []
    # Split IDs into chunks; use & continuation for multi-line group command.
    # LAMMPS accumulates atoms when the SAME group name + id is repeated
    # only via union/intersect — a second 'group G id ...' RESETS G.
    # Therefore we write a single logical command using & continuation.
    chunks = [na_ids[i:i + IDS_PER_LINE]
              for i in range(0, len(na_ids), IDS_PER_LINE)]

    for k, chunk in enumerate(chunks):
        id_str = " ".join(str(i) for i in chunk)
        is_first = (k == 0)
        is_last  = (k == len(chunks) - 1)

        if is_first and is_last:
            # Single line, no continuation needed
            lines.append(f"group former_Na id {id_str}")
        elif is_first:
            lines.append(f"group former_Na id {id_str} &")
        elif is_last:
            lines.append(f"  {id_str}")
        else:
            lines.append(f"  {id_str} &")

    with open(out_path, 'w') as f:
        f.write("# Auto-generated by extract_na_ids.py\n")
        f.write(f"# Atom IDs that were Na (type 4) in AM parent — {len(na_ids)} atoms\n")
        f.write("\n".join(lines) + "\n")

    print(f"Written: {out_path}  ({len(na_ids)} Na IDs)")


def main():
    if len(sys.argv) != 3:
        print("Usage: python3 extract_na_ids.py <x_parent> <r>")
        sys.exit(1)

    x_parent = int(sys.argv[1])
    r        = int(sys.argv[2])

    am_path  = Path(str(AM_DATA).format(xp=x_parent, r=r))
    out_path = OUT_DIR / f"na_ids_xp{x_parent}_r{r}.lmp"

    if not am_path.exists():
        print(f"ERROR: AM data file not found:\n  {am_path}")
        sys.exit(1)

    OUT_DIR.mkdir(parents=True, exist_ok=True)

    print(f"Reading AM data: {am_path}")
    na_ids = read_na_ids(am_path)
    print(f"Found {len(na_ids)} Na atoms (type 4) in AM x={x_parent} r={r}")

    write_lammps_group(na_ids, out_path)


if __name__ == "__main__":
    main()
